services:
  lizzy:
    image: moonded/lizzyfuzzy:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - "./.env:/.env"
      - "/etc/letsencrypt/live/backend.redmodding.org/fullchain.pem:./src/keys/fullchain.pem"
      - "/etc/letsencrypt/live/backend.redmodding.org/privkey.pem:./src/keys/privkey.pem"
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - db
    networks:
      - lizzy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fe0c836613916e4f97be69054a56798f
    ports:
      - "5432:5432"
    networks:
      - lizzy

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://host.docker.internal:8081/render
      GF_RENDERING_CALLBACK_URL: http://host.docker.internal:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - lizzy
  renderer:
    image: grafana/grafana-image-renderer
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - lizzy

networks:
  lizzy:
    driver: bridge
