services:
  lizzy:
    image: lizzy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - lizzy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lizzy
    ports:
      - "5432:5432"
    networks:
      - lizzy

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://host.docker.internal:8081/render
      GF_RENDERING_CALLBACK_URL: http://host.docker.internal:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - lizzy
  renderer:
    image: grafana/grafana-image-renderer
    ports:
      - "8081:8081"


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - lizzy

networks:
  lizzy:
    driver: bridge
