services:
  lizzy:
    image: moonded/lizzyfuzzy:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - "./.env:/.env"
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fe0c836613916e4f97be69054a56798f
    ports:
      - "5432:5432"

  api:
    image: moonded/lizzyapi:latest
    volumes:
      - "./.env:/.env"
      - "/etc/letsencrypt/live/backend.redmodding.org/fullchain.pem:./src/keys/fullchain.pem"
      - "/etc/letsencrypt/live/backend.redmodding.org/privkey.pem:./src/keys/privkey.pem"
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - db
